# Site settings
title: Munpyo Hong
email: skkhmp@skku.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skkhmp.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
#google_author: 
#google_site_verification: 
#bing_webmastertools_id: 
